# Generated by Django 2.2 on 2020-01-28 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='地理位置名称')),
                ('address', models.CharField(default='', max_length=100, verbose_name='所在地')),
                ('intr', models.TextField(default='', verbose_name='介绍')),
            ],
            options={
                'verbose_name': '地理位置',
                'verbose_name_plural': '地理位置',
            },
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='套餐名称')),
                ('location', models.CharField(default='', max_length=50, verbose_name='目的地')),
                ('price', models.CharField(default='', max_length=20, verbose_name='价格')),
                ('numbers', models.IntegerField(default=1, verbose_name='套餐包含人数')),
                ('evaluation', models.FloatField(default=3.0, verbose_name='评分')),
                ('intr', models.CharField(default='', max_length=200, verbose_name='简介')),
                ('image', models.ImageField(default='', upload_to='images/%Y/%m', verbose_name='照片')),
            ],
            options={
                'verbose_name': '旅游套餐',
                'verbose_name_plural': '旅游套餐',
            },
        ),
        migrations.CreateModel(
            name='Viewpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='景点名称')),
                ('numbers', models.IntegerField(default=0, verbose_name='旅游人数')),
                ('score', models.CharField(default='0', max_length=20, verbose_name='评分')),
                ('intr', models.CharField(default='', max_length=200, verbose_name='简介')),
                ('detail', models.TextField(default='', verbose_name='详细介绍')),
                ('image', models.ImageField(default='', upload_to='images/%Y/%m', verbose_name='照片')),
                ('address', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='viewpoint.Location', verbose_name='位置')),
            ],
            options={
                'verbose_name': '景点信息',
                'verbose_name_plural': '景点信息',
            },
        ),
    ]
