# Generated by Django 2.2 on 2020-01-31 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewpoint', '0002_location_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images/%Y/%m', verbose_name='照片')),
            ],
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='pics',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='viewpoint.Image', verbose_name='相关照片'),
        ),
    ]
