# Generated by Django 2.2 on 2020-01-31 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewpoint', '0004_auto_20200131_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='pics',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='viewpoint.Image', verbose_name='相关照片'),
        ),
    ]
