# Generated by Django 2.2 on 2020-01-31 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewpoint', '0005_travelpackage_pics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpackage',
            name='pics',
        ),
        migrations.AddField(
            model_name='image',
            name='view_img_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='viewpoint.TravelPackage'),
        ),
    ]
