# Generated by Django 2.2 on 2020-01-31 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewpoint', '0006_auto_20200131_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='package_img_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='viewpoint.TravelPackage'),
        ),
        migrations.AlterField(
            model_name='image',
            name='view_img_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='viewpoint.Viewpoint'),
        ),
    ]
