# Generated by Django 2.2 on 2020-01-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpoint', '0008_auto_20200131_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageimage',
            name='intr',
            field=models.CharField(default='', max_length=100, verbose_name='描述'),
        ),
    ]
