# Generated by Django 2.2 on 2020-01-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpoint', '0009_packageimage_intr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimage',
            name='image',
            field=models.ImageField(default='', upload_to='images/%Y/%m', verbose_name='套餐照片'),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='intr',
            field=models.CharField(default='...', max_length=100, verbose_name='描述'),
        ),
    ]
