# Generated by Django 2.2 on 2020-01-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpoint', '0011_auto_20200131_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimage',
            name='intr',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='viewimage',
            name='intr',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='描述'),
        ),
    ]
