# Generated by Django 2.2 on 2020-01-31 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpoint', '0012_auto_20200131_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageimage',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 21, 21, 33, 262731), verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='viewimage',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 21, 21, 33, 263729), verbose_name='添加时间'),
        ),
    ]
