# Generated by Django 2.2 on 2020-01-31 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpoint', '0013_auto_20200131_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimage',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 21, 22, 32, 811560), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='viewimage',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 21, 22, 32, 813556), verbose_name='添加时间'),
        ),
    ]
