# Generated by Django 2.2 on 2020-01-31 21:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewpoint', '0014_auto_20200131_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimage',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 21, 25, 8, 680937), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='viewimage',
            name='addtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 31, 21, 25, 8, 682929), null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='viewimage',
            name='view_img_list',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='viewpoint.Viewpoint'),
        ),
    ]
