# Generated by Django 2.0 on 2020-01-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='企业名称')),
                ('address', models.CharField(max_length=100, verbose_name='企业地址')),
                ('detail', models.TextField(default='', verbose_name='企业简介')),
            ],
            options={
                'verbose_name_plural': '企业信息',
                'verbose_name': '企业信息',
            },
        ),
    ]
